name: Playwright Tests

permissions:
  contents: read
  checks: write
  id-token: write

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Create .env file
        run: echo "DEMO_BASE_URL=https://hypersequent.github.io/food-delivery-demo/" > .env

      - name: Run Playwright tests
        run: npx playwright test
        env:
          API_KEY: ${{ secrets.API_KEY }}

      - name: Generate Allure Report
        if: always()
        run: pnpm run allure-report

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-test-results
          path: test-results/

      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-test-results
          path: allure-report/

      - name: Publish JUnit Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'junit-results/*.xml'
